name: RenderDeploy

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    tags:
      - "v*"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      ##- name: Set up cache
      ##  uses: actions/cache@v4.0.0
      ##  with:
      ##    path: |
      ##      **/build
      ##    key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
      ##    restore-keys: |
      ##      ${{ runner.os }}-gradle-

      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: temurin
          architecture: x64
          cache: 'gradle'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3

      - name: Login to DockerHub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Jar , Build Image and Push to dockerhub
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USERNAME }}
        working-directory: ./backend
        run: ./gradlew docker-push -x test --no-daemon
        
      - name: Trigger Render deploy
        run: curl -X GET --location "${{ secrets.RENDER_DEPLOY }}"
